package bb.org.bd.constants;

public class Queries {

	// String string = String.format("A String %s %2d", aStringVar, anIntVar);

	/*
	 * String str = "Entered number = %d and string = %s";
	 * 
	 * List<Object> args = new ArrayList<Object>(); args.add(1);
	 * args.add("abcd");
	 * 
	 * System.out.println(String.format(str, args.toArray()));
	 */

	public static String findLcdByLcID_Vua = "SELECT  ROW_NUMBER() OVER ( ORDER BY A.LC_ID) AS SL_NO, A.* " + " FROM( "
			+ "     SELECT LC_ID,LC_DATE,NVL(LC_EXPIRY_DATE, ADD_MONTHS(LC_DATE,18))  LC_EXPIRY_DATE ,NVL(LAST_SHIPMENT_DATE, "
			+ "     ADD_MONTHS(LC_DATE,18)) LAST_SHIPMENT_DATE ,UPDATE_STATUS  ,UPDATEDATE,LC_AMOUNT, "
			+ "     CASE  CURRENCY_CODE WHEN '098' THEN '001' WHEN '047' THEN '086' ELSE CURRENCY_CODE END   CURRENCY_CODE,COUNTRY_CODE , "
			+ "     CASE  T1.BIN1 WHEN 0 THEN T2.BIN  ELSE T1.BIN1 END BIN, "
			+ "     STRING_SHAPE(IMP_NAME,3) IMP_NAME ,  NVL(STRING_SHAPE(BENEFICIARY_NAME,3),'-') BENEFICIARY_NAME "
			+ "     FROM( " + " SELECT T1.* , T2.IMP_REGNO " + "         FROM( "
			+ "             SELECT A1.*, NVL(TO_CHAR(A1.UPD_DATE,'yyyy-mm-dd'), TO_CHAR(A1.LC_DATE,'yyyy-mm-dd')) UPDATEDATE, NVL(A1.BIN,0) BIN1 FROM LC_INFO A1 "
			+ "             WHERE LC_ID =  %d  AND FINAL_YN ='Y' AND UPDATE_STATUS >= 0 "
			+ "             ) T1 LEFT JOIN  LCAF T2 ON T1.LCAF_ID =T2.LCAF_ID "
			+ "         ) T1 LEFT JOIN (SELECT IMP_REGNO ,NVL(BIN,0) BIN, IMP_NAME   FROM IMPORTER) T2 ON T1.IMP_REGNO =  T2.IMP_REGNO "
			+ "     ) A";;

	public static String findLcdByLcID = "SELECT LPAD(TO_CHAR(LC_INFOS.LC_ID),16,'0' ) LC_ID, LC_INFOS.LC_DATE, NVL(LC_INFOS.LC_EXPIRY_DATE, ADD_MONTHS(LC_DATE,18)) LC_EXPIRY_DATE, "
			+ " NVL(LAST_SHIPMENT_DATE,ADD_MONTHS(LC_INFOS.LC_DATE,18)) LAST_SHIPMENT_DATE, LC_INFOS.UPDATE_STATUS, LC_INFOS.UPDATEDATE UPDATE_DATE, LC_INFOS.LC_AMOUNT, "
			+ " GET_CURR_ABBR_CUST(CASE LC_INFOS.CURRENCY_CODE WHEN '098' THEN '001' WHEN '047' THEN '086' ELSE LC_INFOS.CURRENCY_CODE END) CURRENCY,  "
			+ " GET_COUNTRY_ISOCUST(LC_INFOS.COUNTRY_CODE) COUNTRY_CODE_IMP, "
			+ " NVL(CASE  LC_INFOS.BIN1 WHEN 0 THEN NVL(IMPORTER.BIN,0) ELSE LC_INFOS.BIN1 END,0) BIN, "
			+ " NVL(STRING_SHAPE(IMPORTER.IMP_NAME,3), '-') IMPORTERNAME , SUBSTR(STRING_SHAPE(NVL(STRING_SHAPE(BENEFICIARY_NAME,3),'-') ,3), 1, 100 ) BENEFICIARY, "
			+ " SUBSTR(LC_DETAIL.COMMODITY_CODE, 3, 8) COMMODITY_CODE, NVL(GET_ISO_UNITCUST(LC_DETAIL.UNIT_CODE),'NA') UNIT_CODE, LC_DETAIL.UNIT_PRICE, "
			+ " LC_DETAIL.QUANTITY, GET_COUNTRY_ISOCUST(LC_DETAIL.COUNTRY_CODE) COUNTRY_CODE_ORG, SUBSTR(NVL(STRING_SHAPE(LC_DETAIL.PI_COMM_DESC,3),'-'),1,100) DESCRIPTION "
			+ " FROM " + " ( "
			+ " SELECT LC_INFO.*, NVL(TO_CHAR(LC_INFO.UPD_DATE,'YYYY-MM-DD'), TO_CHAR(LC_INFO.LC_DATE,'YYYY-MM-DD') ) UPDATEDATE, NVL(LC_INFO.BIN,0) BIN1 FROM LC_INFO "
			+ " WHERE LC_ID = TO_NUMBER('%s') AND FINAL_YN ='Y' AND UPDATE_STATUS >= 0 " + " ) LC_INFOS  "
			+ " LEFT JOIN  LCAF ON LC_INFOS.LCAF_ID =LCAF.LCAF_ID "
			+ " LEFT JOIN IMPORTER ON LCAF.IMP_REGNO =  IMPORTER.IMP_REGNO "
			+ " LEFT JOIN LC_DETAIL ON LC_INFOS.LC_ID = LC_DETAIL.LC_ID ";

	public static String findLcsByDate = "SELECT LPAD(TO_CHAR(LC_INFOS.LC_ID),16,'0' ) LC_ID, LC_INFOS.LC_DATE, NVL(LC_INFOS.LC_EXPIRY_DATE, ADD_MONTHS(LC_DATE,18)) LC_EXPIRY_DATE, "
			+ " NVL(LAST_SHIPMENT_DATE,ADD_MONTHS(LC_INFOS.LC_DATE,18)) LAST_SHIPMENT_DATE, LC_INFOS.UPDATE_STATUS, LC_INFOS.UPDATEDATE UPDATE_DATE, LC_INFOS.LC_AMOUNT, "
			+ " GET_CURR_ABBR_CUST(CASE LC_INFOS.CURRENCY_CODE WHEN '098' THEN '001' WHEN '047' THEN '086' ELSE LC_INFOS.CURRENCY_CODE END) CURRENCY,  "
			+ " GET_COUNTRY_ISOCUST(LC_INFOS.COUNTRY_CODE) COUNTRY_CODE_IMP, "
			+ " NVL(CASE  LC_INFOS.BIN1 WHEN 0 THEN NVL(IMPORTER.BIN,0) ELSE LC_INFOS.BIN1 END,0) BIN, "
			+ " NVL(STRING_SHAPE(IMPORTER.IMP_NAME,3), '-') IMPORTERNAME , SUBSTR(STRING_SHAPE(NVL(STRING_SHAPE(BENEFICIARY_NAME,3),'-') ,3), 1, 100 ) BENEFICIARY, "
			+ " SUBSTR(LC_DETAIL.COMMODITY_CODE, 3, 8) COMMODITY_CODE, NVL(GET_ISO_UNITCUST(LC_DETAIL.UNIT_CODE),'NA') UNIT_CODE, LC_DETAIL.UNIT_PRICE, "
			+ " LC_DETAIL.QUANTITY, GET_COUNTRY_ISOCUST(LC_DETAIL.COUNTRY_CODE) COUNTRY_CODE_ORG, SUBSTR(NVL(STRING_SHAPE(LC_DETAIL.PI_COMM_DESC,3),'-'),1,100) DESCRIPTION "
			+ " FROM " + " ( "
			+ " SELECT A1.*, NVL(TO_CHAR(A1.UPD_DATE,'YYYY-MM-DD'), TO_CHAR(A1.LC_DATE,'YYYY-MM-DD')  ) UPDATEDATE, NVL(A1.BIN,0) BIN1 FROM LC_INFO A1 "
			+ " WHERE TRUNC(ENT_DATE) = TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND FINAL_YN ='Y' AND UPD_DATE IS NULL AND UPDATE_STATUS = 0 "
			+ " UNION ALL "
			+ " SELECT A1.*, NVL(TO_CHAR(A1.UPD_DATE,'YYYY-MM-DD'), TO_CHAR(A1.LC_DATE,'YYYY-MM-DD') ) UPDATEDATE, NVL(A1.BIN,0) BIN1 FROM LC_INFO A1 "
			//+ " WHERE TRUNC(UPD_DATE)  = TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND TRUNC(ENT_DATE)  <= TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND FINAL_YN ='Y' AND UPDATE_STATUS > 0 "
			+ " WHERE TRUNC(UPD_DATE)  = TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND TRUNC(UPD_DATE)  <= TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND FINAL_YN ='Y' AND UPDATE_STATUS > 0 "
			+ " ) LC_INFOS  " + " LEFT JOIN  LCAF ON LC_INFOS.LCAF_ID =LCAF.LCAF_ID "
			+ " LEFT JOIN IMPORTER ON LCAF.IMP_REGNO =  IMPORTER.IMP_REGNO "
			+ " LEFT JOIN LC_DETAIL ON LC_INFOS.LC_ID = LC_DETAIL.LC_ID ";

	public static String findLcsByDateAndTimeRange = "SELECT LPAD(TO_CHAR(LC_INFOS.LC_ID),16,'0' ) LC_ID, LC_INFOS.LC_DATE, NVL(LC_INFOS.LC_EXPIRY_DATE, ADD_MONTHS(LC_DATE,18)) LC_EXPIRY_DATE, "
			+ " NVL(LAST_SHIPMENT_DATE,ADD_MONTHS(LC_INFOS.LC_DATE,18)) LAST_SHIPMENT_DATE, LC_INFOS.UPDATE_STATUS, LC_INFOS.UPDATEDATE UPDATE_DATE, LC_INFOS.LC_AMOUNT, "
			+ " GET_CURR_ABBR_CUST(CASE LC_INFOS.CURRENCY_CODE WHEN '098' THEN '001' WHEN '047' THEN '086' ELSE LC_INFOS.CURRENCY_CODE END) CURRENCY,  "
			+ " GET_COUNTRY_ISOCUST(LC_INFOS.COUNTRY_CODE) COUNTRY_CODE_IMP, "
			+ " NVL(CASE  LC_INFOS.BIN1 WHEN 0 THEN NVL(IMPORTER.BIN,0) ELSE LC_INFOS.BIN1 END,0) BIN, "
			+ " NVL(STRING_SHAPE(IMPORTER.IMP_NAME,3), '-') IMPORTERNAME , SUBSTR(STRING_SHAPE(NVL(STRING_SHAPE(BENEFICIARY_NAME,3),'-') ,3), 1, 100 ) BENEFICIARY, "
			+ " SUBSTR(LC_DETAIL.COMMODITY_CODE, 3, 8) COMMODITY_CODE, NVL(GET_ISO_UNITCUST(LC_DETAIL.UNIT_CODE),'NA') UNIT_CODE, LC_DETAIL.UNIT_PRICE, "
			+ " LC_DETAIL.QUANTITY, GET_COUNTRY_ISOCUST(LC_DETAIL.COUNTRY_CODE) COUNTRY_CODE_ORG, SUBSTR(NVL(STRING_SHAPE(LC_DETAIL.PI_COMM_DESC,3),'-'),1,100) DESCRIPTION "
			+ " FROM " + " ( "
			+ " SELECT LC_INFO.*, NVL(TO_CHAR(LC_INFO.UPD_DATE,'YYYY-MM-DD'), TO_CHAR(LC_INFO.LC_DATE,'YYYY-MM-DD') ) UPDATEDATE, NVL(LC_INFO.BIN,0) BIN1 FROM LC_INFO "
			+ " WHERE LC_INFO.FINAL_YN ='Y' AND UPDATE_STATUS >= 0 "
			+ " 	AND UPDATE_DATE >= TO_DATE('%s', 'YYYY-MM-DD HH24:MI:SS') "
			+ " 	AND UPDATE_DATE <= TO_DATE('%s', 'YYYY-MM-DD HH24:MI:SS') " + " ) LC_INFOS  "
			+ " LEFT JOIN  LCAF ON LC_INFOS.LCAF_ID =LCAF.LCAF_ID "
			+ " LEFT JOIN IMPORTER ON LCAF.IMP_REGNO =  IMPORTER.IMP_REGNO "
			+ " LEFT JOIN LC_DETAIL ON LC_INFOS.LC_ID = LC_DETAIL.LC_ID ";

	public static String findExpByExpNo = " SELECT A.EXP_NO EXP_NUMBER, NVL(A.AMOUNT_INV,0) AMOUNT, GET_CURR_ABBR_CUST(A.CURRENCY_CODE) CURRENCY_CODE, "
			+ " GET_COUNTRY_ISOCUST(A.COUNTRY_CODE) COUNTRY_CODE, SUBSTR(A.COMMODITY_CODE,3,8) COMMODITY_CODE, "
			+ " CASE  A.BIN1 WHEN 0 THEN B.BIN2 ELSE A.BIN1 END BIN , "
			+ " NVL(A.EXP_REGNO, 'NA') ERC, SUBSTR(NVL(B.EXP_NAME,'NA'),1,35) EXPORTER_NAME, SUBSTR(NVL(B.EXPADDR1,'NA'),1,175) EXPORTER_ADDRESS , "
			+ " NVL(A.UPDATE_STATUS,0) UPDATE_STATUS, NVL(TO_CHAR(A.UPDATE_DATE,'YYYY-MM-DD' ), TO_CHAR(A.ENT_DATE,'YYYY-MM-DD'))  UPDATE_DATE  "
			+ " FROM "
			+ " (SELECT EXP_INFO.* , NVL(BIN,0) BIN1 FROM EXP_INFO ) A LEFT JOIN (SELECT EXPORTERCODE.* , NVL(BIN,0) BIN2 FROM EXPORTERCODE ) B ON A.EXP_REGNO=B.EXP_REGNO "
			+ " WHERE A.DUP_FLAG IS NULL AND A.TRP_FLAG IS NULL AND A.CANCEL_FLAG IS NULL " + " AND EXP_NO = '%s' ";

	public static String findExpByDate = " SELECT A.EXP_NO EXP_NUMBER, NVL(A.AMOUNT_INV,0) AMOUNT, GET_CURR_ABBR_CUST(A.CURRENCY_CODE) CURRENCY_CODE, "
			+ " GET_COUNTRY_ISOCUST(A.COUNTRY_CODE) COUNTRY_CODE, SUBSTR(A.COMMODITY_CODE,3,8) COMMODITY_CODE, "
			+ " CASE  A.BIN1 WHEN 0 THEN B.BIN2 ELSE A.BIN1 END BIN , "
			+ " NVL(A.EXP_REGNO, 'NA') ERC, SUBSTR(NVL(B.EXP_NAME,'NA'),1,35) EXPORTER_NAME, SUBSTR(NVL(B.EXPADDR1,'NA'),1,175) EXPORTER_ADDRESS , "
			+ " NVL(A.UPDATE_STATUS,0) UPDATE_STATUS, NVL(TO_CHAR(A.UPDATE_DATE,'YYYY-MM-DD' ), TO_CHAR(A.ENT_DATE,'YYYY-MM-DD'))  UPDATE_DATE  "
			+ " FROM "
			+ " (SELECT EXP_INFO.* , NVL(BIN,0) BIN1 FROM EXP_INFO ) A LEFT JOIN (SELECT EXPORTERCODE.* , NVL(BIN,0) BIN2 FROM EXPORTERCODE ) B ON A.EXP_REGNO=B.EXP_REGNO "
			+ " WHERE A.DUP_FLAG IS NULL AND A.TRP_FLAG IS NULL AND A.CANCEL_FLAG IS NULL "
			+ " AND TRUNC(A.ENT_DATE) = TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) " + " UNION ALL "
			+ " SELECT A.EXP_NO EXP_NUMBER, NVL(A.AMOUNT_INV,0) AMOUNT, GET_CURR_ABBR_CUST(A.CURRENCY_CODE) CURRENCY_CODE, "
			+ " GET_COUNTRY_ISOCUST(A.COUNTRY_CODE) COUNTRY_CODE, SUBSTR(A.COMMODITY_CODE,3,8) COMMODITY_CODE, "
			+ " CASE  A.BIN1 WHEN 0 THEN B.BIN2 ELSE A.BIN1 END BIN , "
			+ " NVL(A.EXP_REGNO, 'NA') ERC, SUBSTR(NVL(B.EXP_NAME,'NA'),1,35) EXPORTER_NAME, SUBSTR(NVL(B.EXPADDR1,'NA'),1,175) EXPORTER_ADDRESS , "
			+ " NVL(A.UPDATE_STATUS,0) UPDATE_STATUS, NVL(TO_CHAR(A.UPDATE_DATE,'YYYY-MM-DD' ), TO_CHAR(A.ENT_DATE,'YYYY-MM-DD'))  UPDATE_DATE "
			+ " FROM "
			+ " (SELECT EXP_INFO.* , NVL(BIN,0) BIN1 FROM EXP_INFO ) A LEFT JOIN (SELECT EXPORTERCODE.* , NVL(BIN,0) BIN2 FROM EXPORTERCODE ) B ON A.EXP_REGNO=B.EXP_REGNO "
			+ " WHERE A.DUP_FLAG IS NULL AND A.TRP_FLAG IS NULL AND A.CANCEL_FLAG IS NULL "
			+ " AND  TRUNC(A.ENT_DATE) < TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) AND TRUNC(A.UPDATE_DATE) = TRUNC(TO_DATE('%s', 'YYYY-MM-DD')) ";

	public static String findExpByDateAndTimeRange = " SELECT A.EXP_NO EXP_NUMBER, NVL(A.AMOUNT_INV,0) AMOUNT, GET_CURR_ABBR_CUST(A.CURRENCY_CODE) CURRENCY_CODE, "
			+ " GET_COUNTRY_ISOCUST(A.COUNTRY_CODE) COUNTRY_CODE, SUBSTR(A.COMMODITY_CODE,3,8) COMMODITY_CODE, "
			+ " CASE  A.BIN1 WHEN 0 THEN B.BIN2 ELSE A.BIN1 END BIN , "
			+ " NVL(A.EXP_REGNO, 'NA') ERC, SUBSTR(NVL(B.EXP_NAME,'NA'),1,35) EXPORTER_NAME, SUBSTR(NVL(B.EXPADDR1,'NA'),1,175) EXPORTER_ADDRESS , "
			+ " NVL(A.UPDATE_STATUS,0) UPDATE_STATUS, NVL(TO_CHAR(A.UPDATE_DATE,'YYYY-MM-DD' ), TO_CHAR(A.ENT_DATE,'YYYY-MM-DD'))  UPDATE_DATE  "
			+ " FROM "
			+ " (SELECT EXP_INFO.* , NVL(BIN,0) BIN1 FROM EXP_INFO ) A LEFT JOIN (SELECT EXPORTERCODE.* , NVL(BIN,0) BIN2 FROM EXPORTERCODE ) B ON A.EXP_REGNO=B.EXP_REGNO "
			+ " WHERE A.DUP_FLAG IS NULL AND A.TRP_FLAG IS NULL AND A.CANCEL_FLAG IS NULL "
			+ " AND A.UPDATE_DATE >= TO_DATE('%s', 'YYYY-MM-DD HH24:MI:SS') "
			+ " AND A.UPDATE_DATE <= TO_DATE('%s', 'YYYY-MM-DD HH24:MI:SS')";

}
